server:
  port: 8080

spring:
  datasource:
    username: root
#    password: 6225110
    password: xdnlcf
    url: jdbc:mysql://localhost:3306/bres?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entit
  # spring boot集成mybatis的方式打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#showSql
logging:
  level:
    com.tj.mapper: trace

#    com:
#      example:
#        mapper : info
  file:
    path: D:/java/myLog

debug: true
